### ISSUE TITLE
:bug: CORS Error 

### ISSUE THREAD

**Issue by devbtech** [ChildMindInstitute/mindlogger-app-backend#662]
After I tested PR [#660](https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/660) is the latest updates we fixed 500 error([#776](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-app/776)), I can confirm single/daily events are all saved successfully. But what I am going to mention here is we are still having CORS errors rarely happens while calling API in [admin panel](https://admin.mindlogger.org).

**Comment by devbtech** [comment]
Here's a screenshot of when it occurs
![image.png](https://images.zenhubusercontent.com/5e248ca6aaf6ad9f4a061291/2e9354b5-39e4-4c99-9935-2a90e356075c)

**Comment by shnizzedy** [comment]
For context, I think the underlying behavior that causes this error is the request timing out before the CORS header is returned.

https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/236#issuecomment-558339065

**Comment by devbtech** [comment]
@shnizzedy Thanks for your comment! Here's my thoughts. As far as I know, this is server side erro. When the request comes to server, frontend sends original host where this request comes from and the server rejects it if it's not their registered host and responses the error immediately to front-end and some of requests couldn't run on the server side. I installed `chrrypy_cors` module to allow accepting frontend request on server - this will resolve CORS error. What's your thought?

**Comment by devbtech** [comment]
@shnizzedy Thanks for your comment! Here's my thoughts. As far as I know, this is server side error. When the request comes to server, frontend sends original host where this request comes from and the server rejects it if it's not their registered host and responses the error immediately to front-end and some of requests couldn't run on the server side. I installed `chrrypy_cors` module to allow accepting frontend request on server - this will resolve CORS error. What's your thought?

**Comment by devbtech** [comment]
you can check it's installed in `[1e47bb62](https://github.com/ChildMindInstitute/mindlogger-app-backend/pull/664/commits/1e47bb626c9a3d90fc067421909c2da2089db9c5)`

**Comment by shnizzedy** [comment]
As far as I've seen, CORS isn't really the problem; it's always worked as expected for small requests and failed for requests that timeout. If cherrypy_corrs helps, I think it's expedience at a potential cost in security. Check out [Girder: Security: CORS (Cross-Origin Resource Sharing)](https://girder.readthedocs.io/en/stable/security.html#cors-cross-origin-resource-sharing) for what's included off the shelf.

Here are the current Girder CORS settings on dev
```yaml
CORS Allowed Origins: *
CORS Allowed Methods: GET, POST, PUT, HEAD, DELETE, OPTIONS
CORS Allowed Headers: access_token, Accept-Encoding, Authorization, Content-Disposition, Content-Type, Cookie, Girder-Authorization, Girder-OTP, Girder-Token, Access-Control-Allow-Origin, Access-Control-Allow-Origin:
```
and on prod
```yaml
CORS Allowed Origins: *
CORS Allowed Methods: GET, POST, PUT, HEAD, DELETE, OPTIONS
CORS Allowed Headers: access_token, Accept-Encoding, Authorization, Content-Disposition, Content-Type, Cookie, Girder-Authorization, Girder-OTP, Girder-Token, Access-Control-Allow-Origin, Access-Control-Allow-Origin:
```
